### ISSUE TITLE
Update default template to something lighter

### ISSUE THREAD

**Issue by MoOx** [Documented-Style-Sheets/grunt-dss#13]
What do you think about having a lighter template that use BEM approch to scope styles correctly ?

Avoid reset, & default styles (with tag) and add a `dss-Styleguide` prefix on all className of items ?

Look what my template look like right now:

![screen shot 2013-05-13 at 3 30 07 pm](https://f.cloud.github.com/assets/157534/495773/522e5234-bbd1-11e2-8961-c272a63600c6.png)
![screen shot 2013-05-13 at 3 30 24 pm](https://f.cloud.github.com/assets/157534/495774/5513a558-bbd1-11e2-9377-039c89b788ca.png)

This seems to bloat the code, but it can avoid having conflict with default styles of the styleguide default styles.
What do you think ?

**Comment by kud** [comment]
:+1:

**Comment by kud** [comment]
even :shipit:

**Comment by MoOx** [comment]
I can make a PR if @darcyclarke is interested ;)

**Comment by kud** [comment]
I am, ain't enough?

**Comment by darcyclarke** [comment]
Hmm, I think I was trying to avoid this because I eventually wanted to properly scope each example using `iframe`s. @MoOx could you look into that first. If not, I'll look into it asap (obviously have a backlog of issues here now).
