### ISSUE TITLE
Is all prettify languages required in default template ?

### ISSUE THREAD

**Issue by MoOx** [Documented-Style-Sheets/grunt-dss#14]
Maybe something like [prismjs](https://github.com/LeaVerou/prism) can be lighter for html & css ?

**Comment by darcyclarke** [comment]
Latest commit should address the size issue. A redesign of the default template with different syntax highlighting is always welcome. Or, creating multiple "themes" may be a nice idea so people have different default options right away (https://github.com/darcyclarke/grunt-dss/commit/867744e0061cdaf056ea4335f8209406a092cb25)
