### ISSUE TITLE
Multiline markup

### ISSUE THREAD

**Issue by weshardee** [Documented-Style-Sheets/grunt-dss#23]
I see that DSS has been edited to use multiline markup examples. Can we get that change integrated into grunt-dss as well?

All in all, this is a great tool.

**Comment by jepek** [comment]
+1

**Comment by espenak** [comment]
Multiline markup would be great. Complex examples are more or less unreadable when all the whitespace disappears.

**Comment by jeffjewiss** [comment]
Hey guys, I think it was just an issue of the version number of DSS referenced in the dependencies.

I've tagged a new version and published it to NPM. Could you please give V1.0.8 a try in your current workflow and let me know if that works?

**Comment by weshardee** [comment]
Perfect. Thanks!
