### ISSUE TITLE
How state markup works ?

### ISSUE THREAD

**Issue by MoOx** [Documented-Style-Sheets/grunt-dss#5]
I run the example & get this:

![Screen Shot 2013-03-18 at 6 56 37 PM](https://f.cloud.github.com/assets/157534/271965/422da0a4-8ff5-11e2-862d-781229f9b9a7.png)

Is it a bug ? Are the examples up to date ?

**Comment by darcyclarke** [comment]
This should be fixed now @MoOx. Sorry about that, it was fixed last week but when I separated the project into 2 projects (the grunt-task and the parser) we missed a merge/commit somewhere somehow. Thanks for noting this. If you grab the latest `grunt-dss` from NPM or pull from master you should be able to build a full example properly. Thanks again for all the early support! Keep it up! It's motivating for me and really helpful to the library.

**Comment by darcyclarke** [comment]
Sorry, forgot to mention the commit: https://github.com/darcyclarke/grunt-dss/commit/9ac17c8a2715bede330bd4fed3ba8e4648ce1542

**Comment by MoOx** [comment]
Cool thanks for the quick fix !

Btw: why did you do all that PR for yourself ? Do you know that you can merge without this ? What app do you use for git ?

**Comment by darcyclarke** [comment]
@MoOx I like to have a process in place for making PRs, every now and then I break that workflow and make a commit straight to `master` but I think that it's in bad taste if I do that. Technically, I should be having other collaborators/contributors double checking and signing off on my own PRs to ensure we aren't pushing bad code into the `master` branch.
